name: Setup Gradle
description: 💿 A simple composite GitHub Action to setup Gradle Build Tool
author: Tozy Fullbuster
inputs:
  ### These inputs below are copied from https://github.com/actions/setup-java/blob/1f2faad7e0bc7efd1f6da4ca0a0f2b23b03a3a7d/action.yml
  java-version:
    description: The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
    default: '17'

  java-version-file:
    description: The path to the `.java-version` file. See examples of supported syntax in README file

  distribution:
    description: Java distribution. See the list of supported distributions in README file
    required: true
    default: zulu

  java-package:
    description: The package type (jdk, jre, jdk+fx, jre+fx)
    required: false
    default: jdk

  architecture:
    description: The architecture of the package (defaults to the action runner's architecture)
    required: false

  jdkFile:
    description: Path to where the compressed JDK is located
    required: false

  check-latest:
    description: Set this option if you want the action to check for the latest available version that satisfies the version spec
    required: false
    default: 'false'

  job-status:
    description: Workaround to pass job status to post job step. This variable is not intended for manual setting
    default: ${{ job.status }}

  token:
    description: |
      The token used to authenticate when fetching version manifests hosted on github.com, such as for the Microsoft Build of OpenJDK.
      When running this action on github.com, the default value is sufficient.
      When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

  # These input below are copied from https://github.com/gradle/gradle-build-action/blob/bde650d6f1426615a60165575bc9cdad3e54d975/action.yml
  gradle-version:
    description: Gradle version to use. If specified, this Gradle version will be downloaded, added to the PATH and used for invoking Gradle.
    required: false

  gradle-executable:
    description: Path to the Gradle executable. If specified, this executable will be added to the PATH and used for invoking Gradle.
    required: false

  build-root-directory:
    description: Path to the root directory of the build. Default is the root of the GitHub workspace.
    required: false

  cache-disabled:
    description: When 'true', all caching is disabled. No entries will be written to or read from the cache.
    required: false
    default: 'false'

  cache-read-only:
    description: |
      When 'true', existing entries will be read from the cache but no entries will be written.
      By default this value is 'false' for workflows on the GitHub default branch and 'true' for workflows on other branches.
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}

  cache-write-only:
    description: |
      When 'true', entries will not be restored from the cache but will be saved at the end of the Job. 
      Setting this to 'true' implies cache-read-only will be 'false'.
    required: false
    default: 'false'

  gradle-home-cache-includes:
    description: Paths within Gradle User Home to cache.
    required: false
    default: |
      caches
      notifications

  gradle-home-cache-excludes:
    description: Paths within Gradle User Home to exclude from cache.
    required: false
  # e.g. Use the following setting to prevent the local build cache from being saved/restored
  #      gradle-home-cache-excludes: |
  #           caches/build-cache-1

  arguments:
    description: Gradle command line arguments (supports multi-line input)
    required: false

  generate-job-summary:
    description: When 'false', no Job Summary will be generated for the Job.
    required: false
    default: 'true'

  # EXPERIMENTAL & INTERNAL ACTION INPUTS
  # The following action properties allow fine-grained tweaking of the action caching behaviour.
  # These properties are experimental and not (yet) designed for production use, and may change without notice in a subsequent release of `gradle-build-action`.
  # Use at your own risk!
  gradle-home-cache-strict-match:
    description: When 'true', the action will not attempt to restore the Gradle User Home entries from other Jobs.
    required: false
    default: 'false'

  workflow-job-context:
    description: Used to uniquely identify the current job invocation. Defaults to the matrix values for this job; this should not be overridden by users (INTERNAL).
    required: false
    default: ${{ toJSON(matrix) }}

  gradle-home-cache-cleanup:
    description: When 'true', the action will attempt to remove any stale/unused entries from the Gradle User Home prior to saving to the GitHub Actions cache.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Java JDK
      id: java
      uses: actions/setup-java@v3.11.0
      with:
        java-version: ${{ inputs.java-version }}
        java-version-file: ${{ inputs.java-version-file }}
        distribution: ${{ inputs.distribution }}
        java-package: ${{ inputs.java-package }}
        architecture: ${{ inputs.architecture }}
        jdkFile: ${{ inputs.jdkFile }}
        check-latest: ${{ inputs.check-latest }}
        job-status: ${{ inputs.job-status }}
        token: ${{ inputs.token }}

    - name: Gradle Build Action
      id: gradle
      uses: gradle/gradle-build-action@v2.5.1
      with:
        gradle-version: ${{ inputs.gradle-version }}
        gradle-executable: ${{ inputs.gradle-executable }}
        build-root-directory: ${{ inputs.build-root-directory }}
        cache-disabled: ${{ inputs.cache-disabled }}
        cache-read-only: ${{ inputs.cache-read-only }}
        cache-write-only: ${{ inputs.cache-write-only }}
        gradle-home-cache-includes: ${{ inputs.gradle-home-cache-includes }}
        gradle-home-cache-excludes: ${{ inputs.gradle-home-cache-excludes }}
        arguments: ${{ inputs.arguments }}
        generate-job-summary: ${{ inputs.generate-job-summary }}
        gradle-home-cache-strict-match: ${{ inputs.gradle-home-cache-strict-match }}
        workflow-job-context: ${{ inputs.workflow-job-context }}
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup }}
